### PR TITLE
make /fuckme command

### PR DESCRIPTION
**Pull request by BradleyJey**
when executed killed you will be

### CODE REVIEW

**Comment by legoboy0215** [comment]
WTF.

**Comment by BradleyJey** [comment]
isnt it a good idea? $p->sendMessage(TextFormat::GREEN."You got fucked too hard by harambe and died!");

**Comment by YaBoiBalAnce** [comment]
Dont even want to fucking know what the hell is wrong with you. But ill merge it cause why tf not

**Comment by legoboy0215** [comment]
Bro WTF squash the commits.

**Comment by BradleyJey** [comment]
😂

Get Outlook for Androidhttps://aka.ms/ghei36

On Fri, Sep 16, 2016 at 10:40 PM -0400, "Legoboy0215" <notifications@github.com<mailto:notifications@github.com>> wrote:

Bro WTF squash the commits.

**Pull request merged**
